config/routes.rb
Longclaw::Application.routes.draw do
  unauthenticated do
    get "extension/refer" => "onboarding#refer"
    get "extension" => "extension#new"
    get "extension/account" => "extension#new"
    get "extension/custom_view" => "extension#new"
  end

  resources :plans
  get 'home/access_denied'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "sessions" }
  # You can have the root of your site routed with "root"

  authenticate :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "home#index", :as => "authenticated_root"

    resources :accounts
    post "/account_bulk" => 'accounts#bulk'
    # get "/update_salesforce" => 'accounts#set_salesforce_account'

    resources :contacts, only: [:create, :update, :destroy]
    resources :projects do
      member do
        get "tasks" => 'projects#tasks_tab'
        get "arg" => 'projects#arg_tab'
        get "filter" => 'projects#filter_timeline'
        get "more" => 'projects#more_timeline'
        get "network_map"
        get "/:time/network_map" => 'projects#network_map'
        get "lookup"
        post "refresh"
      end
      resources :project_subscribers, param: :user_id, only: [:destroy, :create]
      post "project_subscribers/create_all"
    end
    post "/project_bulk" => 'projects#bulk'
    delete "project_subscribers/destroy_other"

    resources :project_members
    resources :users
    post 'user/create' => 'users#create'
    get 'user/me' => 'users#me'
    get 'plans/upgrade' => 'plans#upgrade'
    #resources :plans

    resources :notifications, only: [:index, :update, :create] do
      member do
        get "update_is_complete" => 'notifications#update_is_complete'
        get "download" => 'notifications#download_attachment'
        get "message" => 'notifications#show_message'
      end
      collection do
        post "create_from_suggestion"
      end
    end

    resources :salesforce, only: [:index]
    get "salesforce/disconnect/:id" => 'salesforce#disconnect', as: "salesforce_disconnect"
    post "/link_salesforce_account" => 'salesforce#link_salesforce_account'
    post "/link_salesforce_opportunity" => 'salesforce#link_salesforce_opportunity'
    post "/salesforce/import/:entity_type" => 'salesforce#import_salesforce'
    post "/salesforce/sync" => 'salesforce#sync_salesforce'
    # post "/salesforce_fields_refresh" => 'salesforce#refresh_fields'
    delete "/delete_salesforce_account/:id" => 'salesforce#remove_account_link'
    delete "/delete_salesforce_opportunity/:id" => 'salesforce#remove_opportunity_link'
    post "/salesforce/update_all/:entity_type/:id" => 'salesforce#update_all_salesforce'

    scope "settings", controller: :settings, as: 'settings' do
      get "/" => "settings#index"
      get "users"
      get "alerts"
      post "alerts" => "settings#create_for_alerts"
      get "custom_fields"
      get "custom_lists"
      get "custom_list/:id" => 'settings#custom_list_show'
      get "salesforce_accounts"
      get "salesforce_opportunities"
      get "salesforce_activities"
      get "salesforce_fields/:type" => "settings#salesforce_fields", as: "salesforce_fields"
      get "super_user"
      post "update_user_org" => "settings#organization_jump"
      get "user_analytics"
      post "invite_user/:user_id" => 'settings#invite_user'
    end


    get "/delete_single_activity/:id" => 'activities#destroy'

    resources :activities, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy], shallow: true
      member do
        get 'message' => 'activities#show_message'
      end
    end
    
    resources :organizations


    scope "search", controller: :search, as: 'search' do
      # get "results"
      get "autocomplete_project_name"
      get "autocomplete_contacts"
      get "autocomplete_project_subs"
      get "autocomplete_project_member"
      get "autocomplete_salesforce_account_name"
      get "autocomplete_salesforce_opportunity_name"
    end
    
    scope "reports", controller: :reports, as: 'reports' do
      get 'd_account_success'
      get 'd_account_sales'
      get 'd_team_success'
      get 'd_team_sales'
      get 'd_executive'
      get 'd_competitors'
      get 'accounts_dashboard'
      get 'ad_sort_data/:sort' => 'reports#ad_sort_data', as: :ad_sort_data
      get 'ad_account_data/:id' => 'reports#ad_account_data', as: :ad_account_data
      get 'team_dashboard'
      get 'td_sort_data/:sort/:metric' => 'reports#td_sort_data', as: :td_sort_data
      get 'td_user_data/:id' => 'reports#td_user_data', as: :td_user_data
    end

    scope "extension", controller: :extension, as: 'extension' do
      get '/' => 'extension#index'
      get 'refer'
      get 'test'
      get 'share'
      get 'account'
      get 'company'
      get 'attachments'
      get 'download'
      # get 'alerts_tasks'
      get 'contacts'
      get 'settings'
      post 'save_settings'
      # get 'metrics'
      get 'no_account/:domain', to: 'extension#no_account', as: :no_account
      get 'private_domain'
      get 'project_error'
      # get 'salesforce'
      get 'custom_view'
      get 'salesforce_dashboard'
      post 'create_account'
      get 'dashboard'
      get 'dashboard_drilldown'
    end

    scope "tracking", controller: :tracking, as: 'tracking' do
      post 'create'
      get '/' => 'tracking#index'
      get 'list' => 'tracking#list'
      post 'toggle'
      get 'new_events'
      get 'new_event_objects' => 'tracking#new_event_objects'
      post 'seen'
    end

    resources :entity_fields_metadatum, controller: 'entity_fields_metadata', only: [:create, :update, :destroy] #for /settings/salesforce_fields/standard
    resources :custom_fields, only: [:update]
    resources :custom_fields_metadatum, only: [:create, :update, :destroy]  #for /settings/custom_fields
    resources :custom_lists, only: [:create, :update, :destroy]
    resources :custom_lists_metadata, only: [:create, :update, :destroy]  #for /settings/custom_lists
    resources :custom_configurations, only: [:update, :destroy]

    scope "onboarding", controller: :onboarding, as: 'onboarding' do
      get 'tutorial'
      get 'creating_clusters'
      get 'confirm_projects'
      get 'fill_in_info'
      get 'extension_tutorial'
    end
    post "users/:id/fill_in_info_update" => 'users#fill_in_info_update', :as => 'onboarding_fill_in_info_update'
  end

  # Cluster callback
  post 'onboarding/:user_id/create_clusters' => 'onboarding#create_clusters'

  devise_scope :user do # Unauthenticated user
    get '/auth/:provider/callback' => 'setting#basecamp'
    get "/user/omniauth/auth/:provider", to:  "omniauth_callbacks#user_omniauth_auth_helper", as: "user_omniauth_auth_helper"
    get "/users/auth/salesforcesandbox/callback" => 'omniauth_callbacks#salesforcesandbox'
  end

  scope "webhook", controller: :hooks, as: 'hooks' do
    post "jira"
    post "zendesk"
    post 'fullcontact_person'
    post 'fullcontact_company'
    post 'load_emails_since_yesterday'
    post 'load_events_since_yesterday'
    post 'stripe'
    get 'twilio_sms'
  end

  # twilio textwaittime
  post 'users/create_via_twilio'

  get "track/:user_email/:tracking_id/:gif" => 'tracking#view'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout false, only: ['landing','privacy','terms']
  before_action :check_user_onboarding, only: :index
  before_action :get_current_org_users, only: :index
  before_action :get_current_org_opportunity_stages, only: :index
  before_action :get_current_org_opportunity_forecast_categories, only: :index
  before_action :home_filter_state, only: [:index]

  def index
    # @MEMBERS_LIST_LIMIT = 8 # Max number of Opportunity members to show in mouse-over tooltip

    # Load all projects/opportunities visible to user, belongs to user, and to which user is subscribed
    visible_projects = Project.visible_to(current_user.organization_id, current_user.id)
    visible_projects = visible_projects.close_date_within(params[:close_date]) unless params[:close_date] == 'Any'
    visible_projects = visible_projects.where.not(stage: current_user.organization.get_closed_stages) if params[:close_date] == Project::CLOSE_DATE_RANGE[:ThisQuarterOpen]
    @current_user_projects = visible_projects.owner_of(current_user.id).select("projects.*, false AS daily, false AS weekly")
    subscribed_projects = visible_projects.select("project_subscribers.daily, project_subscribers.weekly").joins(:subscribers).where(project_subscribers: {user_id: current_user.id}).group("project_subscribers.daily, project_subscribers.weekly")

    # Load notifications for "My Alerts & Tasks"
    unless @current_user_projects.blank?
      project_tasks = Notification.where(project_id: @current_user_projects.pluck(:id))
      @open_total_tasks = project_tasks.open.where("assign_to='#{current_user.id}'").sort_by{|t| t.original_due_date.blank? ? Time.at(0) : t.original_due_date }.reverse
      # Need these to show project name and user name instead of pid and uid
      @projects_reverse = @current_user_projects.map { |p| [p.id, p.name] }.to_h
    end

    # Load project data for "My Opportunities"
    @projects = (subscribed_projects + @current_user_projects).uniq(&:id).sort_by{|p| p.name.upcase} # projects/opportunities user owns or to which user is subscribed
    unless @projects.empty?
      project_ids_a = @projects.map(&:id)

      @sparkline = Project.count_activities_by_day_sparkline(project_ids_a, current_user.time_zone)
      @risk_scores = Project.new_risk_score(project_ids_a, current_user.time_zone)
      @open_risk_count = Project.open_risk_count(project_ids_a)
      # @days_to_close = Project.days_to_close(project_ids_a)
      @project_days_inactive = visible_projects.joins(:activities).where.not(activities: { category: [Activity::CATEGORY[:Note], Activity::CATEGORY[:Alert], Activity::CATEGORY[:NextSteps]] }).where('activities.last_sent_date <= ?', Time.current).maximum("activities.last_sent_date") # get last_sent_date
      @project_days_inactive.each { |pid, last_sent_date| @project_days_inactive[pid] = Time.current.to_date.mjd - last_sent_date.in_time_zone.to_date.mjd } # convert last_sent_date to days inactive
      @next_meetings = Activity.meetings.next_week.select("project_id, min(last_sent_date) as next_meeting").where(project_id: project_ids_a).group("project_id")
      @next_meetings = Hash[@next_meetings.map { |p| [p.project_id, p.next_meeting] }]

      #@rag_status = Project.current_rag_score(project_ids_a)
    end

    # Unused metrics
    #@open_tasks_not_overdue = project_tasks.open.where("(original_due_date::date > ? or original_due_date is NULL) and category != '#{Notification::CATEGORY[:Alert]}'", Date.today)
    #@open_risks = project_tasks.open.alerts
    #@overdue_tasks = project_tasks.open.where("original_due_date::date <= ?", Date.today).where("assign_to='#{current_user.id}'")

    #p params
  end

  def daily_summary
    d_tz =  params[:date] || Time.current.strftime('%F')
    @date_with_timezone = Date.parse(d_tz)
    date_filter_offset = Time.current.seconds_since_midnight

    if Date.current <= @date_with_timezone
      where = " between (current_timestamp - interval '#{date_filter_offset} seconds') and current_timestamp"
    else
      where = " between to_timestamp(#{Time.zone.parse(d_tz).utc.to_i}) and (to_timestamp(#{Time.zone.parse(d_tz).utc.to_i}) + interval '24 hours')"
    end

    @sub = current_user.subscriptions.includes(:project)

    if !@sub.nil? and !@sub.empty?
      activities_today = Project.visible_to(current_user.organization_id, current_user.id).following_daily(current_user.id).eager_load([:activities, :account]).where("activities.last_sent_date" + where).group("activities.id, accounts.id")
      @projects_with_activities_today = activities_today.group_by{|e| e.activities.select {|a| a.is_visible_to(current_user) }}

      pinned_activities_today = Project.visible_to(current_user.organization_id, current_user.id).eager_load([:activities]).where("activities.is_pinned = true and activities.pinned_at" + where).group("activities.id")
      @pinned_activities_today = pinned_activities_today.collect { |x| x.activities.select {|a| a.is_visible_to(current_user) }}.flatten
    end
  end

  def access_denied
    render :layout => 'empty'
    # @extension_downloaded = true
    @extension_downloaded = request.user_agent.downcase.match(/chrome/) && cookies[:chromeNotificationBar] == 'false'
    # in case a Basic user signs up through main page, force sign out here so that they will sign in through extension and trigger onboarding
    if current_user.present? && current_user.onboarding_step == Utils::ONBOARDING[:fill_in_info]
      sign_out current_user
    end
  end

  private

  def check_user_onboarding
    if current_user.onboarding_step == Utils::ONBOARDING[:confirm_projects] and !current_user.cluster_create_date.nil?
      redirect_to onboarding_confirm_projects_path
    elsif current_user.onboarding_step == Utils::ONBOARDING[:confirm_projects] and current_user.cluster_create_date.nil?
      redirect_to onboarding_creating_clusters_path
    end
  end

  def home_filter_state
    if params[:close_date]
      cookies[:home_close_date] = {value: params[:close_date]}
    else
      params[:close_date] = cookies[:home_close_date] ? cookies[:home_close_date] : Project::CLOSE_DATE_RANGE[:ThisQuarterOpen]
    end
  end
end

app/views/home/access_denied.html.erb
<div class="lock-word animated fadeInDown">
     <div class="m-t-md">
        <img alt="image" style="width:220px" src="/assets/logo.png">
    </div>
    <span>Oops...</span>
</div>
<div class="middle-box text-center lockscreen animated fadeInDown">
	<div class="m-t-md">
    <p style="font-size:16px;font-weight:200;">Basic and Plus users only<br>have access to our Chrome Extension.</p>
    <% if @extension_downloaded %>
    <!-- Automatically redirect to their Gmail window -->
    <p style="font-size:16px;font-weight:200;">Redirecting you to your Gmail in <span id="countdown-number">5</span>...</p>
    <script type="text/javascript" charset="utf-8">
      setInterval(function () {
        var $timer = $('#countdown-number');
        var countdown = Number($timer.text()) - 1;
        $timer.text(countdown);
          if (countdown <= 0) {
              window.location.replace('https://mail.google.com/mail/?authuser=<%= current_user.nil? ? '' : current_user.email %>');
          }
      }, 1000)
    </script>
    <% else %>
    <!-- Inline install link for extension -->
    <a class="btn btn-primary" href="#" onclick="chrome.webstore.install('https://chrome.google.com/webstore/detail/idihnnlkpfggfgjinfiodninabjggfop', successCallback, failureCallback)">Install our Chrome Extension for Gmail</a>
    <script>
      function successCallback () {
        $('#chrome-notification-bar').hide();
        window.alert('Install successful! Please refresh your Gmail for the extension to take effect.');
      }
      function failureCallback () {
        window.alert('Cannot install extension. Please contact support@contextsmith.com for help.');
      }
    </script>
    <% end %>
	</div>

	<div class="m-t-lg">
		<ul class="list-inline social-icon" style="font-size:18px">
	      <li><a href="https://twitter.com/contextsmith" target="_blank"><i class="fa fa-twitter"></i></a>
	      </li>
	      <li><a href="https://www.facebook.com/ContextSmith" target="_blank"><i class="fa fa-facebook"></i></a>
	      </li>
	      <li><a href="https://www.linkedin.com/company/contextsmith" target="_blank"><i class="fa fa-linkedin"></i></a>
	      </li>
	  </ul>
		<a href="http://www.contextsmith.com">&larr; Back to Homepage</a>
	</div>
</div>

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row m-b-sm filter-group">
        <!-- Empty div here to push warning and filter to right side -->
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="width: 50%; height: 10%; padding-top: 9px">
            <% if @current_user_projects.blank? %> <span style="float: right"><i class="fa fa-exclamation-triangle fa-lg" style="color: <%= ApplicationHelper::CONTEXTSMITH_DARKBLUE %>"></i>&nbsp;The current filter setting has filtered out all opportunities.</span><% end %>
        </div>
        <select id="close-date-filter" class="col-sm-3" data-placeholder="Filter by Close Date" style="width: 24%">
            <option value="Any"></option> <!-- no filter -->
            <optgroup label="By Close Date">
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:Open] %> ><%= Project::CLOSE_DATE_RANGE[:Open] %></option>
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:Closed] %> ><%= Project::CLOSE_DATE_RANGE[:Closed] %></option>
            </optgroup>
            <optgroup label="Quarter">
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:ThisQuarterOpen] %> ><%= Project::CLOSE_DATE_RANGE[:ThisQuarterOpen] %></option>
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:ThisQuarter] %> ><%= Project::CLOSE_DATE_RANGE[:ThisQuarter] %></option>
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:LastQuarter] %> ><%= Project::CLOSE_DATE_RANGE[:LastQuarter] %></option>
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:NextQuarter] %> ><%= Project::CLOSE_DATE_RANGE[:NextQuarter] %></option>
            </optgroup>
            <optgroup label="x-To-Date">
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:QTD] %> ><%= Project::CLOSE_DATE_RANGE[:QTD] %></option>
                <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:YTD] %> ><%= Project::CLOSE_DATE_RANGE[:YTD] %></option>
            </optgroup>
        </select>
    </div>

<!--     <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h2>Most Active (7d)</h2>
                </div>
                <div id="chart-left" class="ibox-content opp-chart"></div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h2>Least Active (7d)</h2>
                </div>
                <div id="chart-center" class="ibox-content opp-chart"></div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h2>Most Open Alerts & Tasks</h2>
                </div>
                <div id="chart-right" class="ibox-content opp-chart"></div>
            </div>
        </div>
    </div> -->

    <!-- Metrics -->


    <div class="row ibox float-e-margins">
        <div class="col-lg-12">
            <div class="ibox-title">
                <table>
                    <tbody>
                        <tr>
                            <td><h2 id="opportunities">My Opportunities<h2></h2>
                            <td>&nbsp;<i class="fa fa-question-circle m-l-xs m-t-xs" data-toggle="tooltip" data-placement="top" data-original-title="Tip: You can modify opportunities like a spreadsheet below"></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="ibox-content">
                <table class="table table-hover nowrap" id="projects-table" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th><%= Project::MAPPABLE_FIELDS_META["stage"] %></th>
                            <th><%= Project::MAPPABLE_FIELDS_META["amount"] %></th>
                            <th><%= Project::MAPPABLE_FIELDS_META["forecast"] %></th>
                            <th>Owner</th>
                            <th></th>
                            <th>Next Steps</th>
                            <th>Next Meeting</th>
                            <th>Close Date</th>
                            <th>Alerts & Tasks</th>
                            <th>Last 7d Activity</th>
                            <th>Days Inactive</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @projects.each do |p| %>
                            <tr>
                                <td>
                                    <div><a href="<%= project_path(p) %>"><%= p.name %></a></div>
                                    <div class="m-t-xs"><small><a class="link-muted" href="<%= account_path(p.account) %>"><%= p.account.name %></a></small></div>
                                </td>
                                <td class="editable-field project-editable-field project-stage-td-<%= p.id %>"><%= best_in_place p, :stage, :as => :select, :collection => @opportunity_stages.map {|s| [s,s]}, inner_class: 'bip-select-input', activator: '.project-stage-td-'+p.id %>&nbsp;&nbsp;<i class="fa fa-pencil editable-field-activator"></i> </td>
                                <td class="editable-field project-editable-field project-amount-td-<%= p.id %>"><%= best_in_place p, :amount, display_with: lambda { |v| v.blank? ? '-' : '$' + number_to_human(v) }, inner_class: 'bip-text-input', activator: '.project-amount-td-'+p.id %>&nbsp;&nbsp;<i class="fa fa-pencil editable-field-activator"></i> </td>
                                <td class="editable-field project-editable-field project-forecast-td-<%= p.id %>"><%= best_in_place p, :forecast, :as => :select, :collection => @opportunity_forecast_categories.map {|s| [s,s]}, inner_class: 'bip-select-input', activator: '.project-forecast-td-'+p.id %>&nbsp;&nbsp;<i class="fa fa-pencil editable-field-activator"></i> </td>
                                <td class="editable-field project-editable-field project-owner-td-<%= p.id %>">
                                  <% if (p.owner_id.nil? || p.owner_id == current_user.id) || current_user.admin? %>
                                    <%= best_in_place p, :owner_id, :as => :select, :collection => @users_reverse, inner_class: 'bip-select-input', activator: '.project-owner-td-'+p.id %>&nbsp;&nbsp;<i class="fa fa-pencil editable-field-activator"></i>
                                  <% else %>
                                    <%= get_full_name(p.project_owner) %>
                                  <% end %></td>
                                <td style="width: 40px">
                                  <% all_members_size = p.users.count + p.contacts.count %>
                                  <span><i class="fa fa-users" style="color:#888"></i> <%= all_members_size %></span>
                                </td>
                                <% ns_activity = p.activities.where(category: Activity::CATEGORY[:NextSteps]).first
                                   ns_updated_at = ns_activity.blank? ? '' : '<small class="text-muted">Updated '.html_safe + time_ago_in_words(ns_activity.last_sent_date.in_time_zone(current_user.time_zone)) + ' ago</small>'.html_safe %>
                                <td class="editable-field project-editable-field project-next-steps-td-<%= p.id %>">
                                  <%= best_in_place p, :next_steps, as: :textarea, ok_button: 'Ok', ok_button_class: 'btn btn-xs btn-primary', inner_class: 'bip-textarea-input', display_with: lambda { |v| simple_format(truncate(word_wrap(CGI.escape_html(v.blank? ? '(none)' : v), line_width: 160), length: 300, separator: '\n') ) }, activator: '.project-next-steps-td-'+p.id %>
                                  <i class="fa fa-pencil editable-field-activator"></i>
                                  <p class="m-b-none"><%= ns_updated_at %></p>
                                </td>
                                <% next_meeting = @next_meetings[p.id].nil? ? "-" : @next_meetings[p.id].strftime('%B %-d (%a) %l:%M%P') %>
                                <% next_meeting_ts = @next_meetings[p.id].nil? ? 0 : @next_meetings[p.id].to_i %>
                                <td data-order="<%= next_meeting_ts %>" style="text-align:center"><%= next_meeting %></td>
                                <td style="text-align:center;" class="editable-field project-editable-field project-close-date-td-<%= p.id %>"><%= best_in_place p, :close_date, as: :date, class: ('text-danger' if p.close_date.present? && p.close_date < Time.current), display_with: lambda { |v| v.blank? ? '-' : v.strftime('%b %-d') }, activator: '.project-close-date-td-'+p.id %>&nbsp;&nbsp;<i class="fa fa-pencil editable-field-activator"></i></td>
                                <td style="text-align:center;" class="<%= @open_risk_count[p.id] > 0 ? 'text-danger' : '' %>"><%=@open_risk_count[p.id].to_s %></td>
                                <td data-sparkline="<%= @sparkline[p.id].join(', ') %>; column"></td>
                                <td style="text-align:center"><%= @project_days_inactive[p.id].nil? ? "-" : @project_days_inactive[p.id] %></td>
                                <td style="width: 120px">
                                    <span data-toggle="tooltip" data-placement="left" data-original-title="Subscribe to daily updates and alerts." data-delay='{"show":"300"}'>
                                    <% if p.daily %>
                                        <%= link_to "<i class=\"fa fa-check\"></i> Daily".html_safe, project_project_subscriber_path(project_id: p.id, user_id: current_user.id) + "?type=daily", remote: true, method: :delete, id: "project-index-unfollow-daily-#{p.id}", class: "block m-b-xs", title: "Following daily" %>
                                    <% else %>
                                        <%= link_to "<i class=\"fa fa-bell-o\"></i> Daily".html_safe, project_project_subscribers_path(project_id: p.id, user_id: current_user.id) + "&type=daily", remote: true, method: :post, id: "project-index-follow-daily-#{p.id}", class: "block m-b-xs", title: "Follow daily" %>
                                    <% end %>
                                    </span>
                                    <span data-toggle="tooltip" data-placement="left" data-original-title="Subscribe to weekly updates and alerts." data-delay='{"show":"300"}'>
                                    <!-- TODO: Uncomment below to undo #1011 -->
                                    <% if p.weekly %>
                                        <!-- < %= link_to "<i class=\"fa fa-check\"></i> Weekly".html_safe, project_project_subscriber_path(project_id: p.id, user_id: current_user.id) + "?type=weekly", remote: true, method: :delete, id: "project-index-unfollow-weekly-#{p.id}", class: "block m-b-xs", title: "Following weekly" %> -->
                                    <% else %>
                                        <!-- < %= link_to "<i class=\"fa fa-bell-o\"></i> Weekly".html_safe, project_project_subscribers_path(project_id: p.id, user_id: current_user.id) + "&type=weekly", remote: true, method: :post, id: "project-index-follow-weekly-#{p.id}", class: "block m-b-xs", title: "Follow weekly" %> -->
                                    <% end %>
                                    </span>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

   
</div>