config/routes.rb
Longclaw::Application.routes.draw do
  unauthenticated do
    get "extension/refer" => "onboarding#refer"
    get "extension" => "extension#new"
    get "extension/account" => "extension#new"
    get "extension/custom_view" => "extension#new"
  end

  resources :plans
  get 'home/access_denied'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "sessions" }
  # You can have the root of your site routed with "root"

  authenticate :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "home#index", :as => "authenticated_root"

    resources :accounts
    post "/account_bulk" => 'accounts#bulk'
    # get "/update_salesforce" => 'accounts#set_salesforce_account'

    resources :contacts, only: [:create, :update, :destroy]
    resources :projects do
      member do
        get "tasks" => 'projects#tasks_tab'
        get "arg" => 'projects#arg_tab'
        get "filter" => 'projects#filter_timeline'
        get "more" => 'projects#more_timeline'
        get "network_map"
        get "/:time/network_map" => 'projects#network_map'
        get "lookup"
        post "refresh"
      end
      resources :project_subscribers, param: :user_id, only: [:destroy, :create]
      post "project_subscribers/create_all"
    end
    post "/project_bulk" => 'projects#bulk'
    delete "project_subscribers/destroy_other"

    resources :project_members
    resources :users
    post 'user/create' => 'users#create'
    get 'user/me' => 'users#me'
    get 'plans/upgrade' => 'plans#upgrade'
    #resources :plans

    resources :notifications, only: [:index, :update, :create] do
      member do
        get "update_is_complete" => 'notifications#update_is_complete'
        get "download" => 'notifications#download_attachment'
        get "message" => 'notifications#show_message'
      end
      collection do
        post "create_from_suggestion"
      end
    end

    resources :salesforce, only: [:index]
    get "salesforce/disconnect/:id" => 'salesforce#disconnect', as: "salesforce_disconnect"
    post "/link_salesforce_account" => 'salesforce#link_salesforce_account'
    post "/link_salesforce_opportunity" => 'salesforce#link_salesforce_opportunity'
    post "/salesforce/import/:entity_type" => 'salesforce#import_salesforce'
    post "/salesforce/sync" => 'salesforce#sync_salesforce'
    # post "/salesforce_fields_refresh" => 'salesforce#refresh_fields'
    delete "/delete_salesforce_account/:id" => 'salesforce#remove_account_link'
    delete "/delete_salesforce_opportunity/:id" => 'salesforce#remove_opportunity_link'
    post "/salesforce/update_all/:entity_type/:id" => 'salesforce#update_all_salesforce'

    scope "settings", controller: :settings, as: 'settings' do
      get "/" => "settings#index"
      get "users"
      get "alerts"
      post "alerts" => "settings#create_for_alerts"
      get "custom_fields"
      get "custom_lists"
      get "custom_list/:id" => 'settings#custom_list_show'
      get "salesforce_accounts"
      get "salesforce_opportunities"
      get "salesforce_activities"
      get "salesforce_fields/:type" => "settings#salesforce_fields", as: "salesforce_fields"
      get "super_user"
      post "update_user_org" => "settings#organization_jump"
      get "user_analytics"
      post "invite_user/:user_id" => 'settings#invite_user'
    end


    get "/delete_single_activity/:id" => 'activities#destroy'

    resources :activities, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy], shallow: true
      member do
        get 'message' => 'activities#show_message'
      end
    end
    
    resources :organizations


    scope "search", controller: :search, as: 'search' do
      # get "results"
      get "autocomplete_project_name"
      get "autocomplete_contacts"
      get "autocomplete_project_subs"
      get "autocomplete_project_member"
      get "autocomplete_salesforce_account_name"
      get "autocomplete_salesforce_opportunity_name"
    end
    
    scope "reports", controller: :reports, as: 'reports' do
      get 'd_account_success'
      get 'd_account_sales'
      get 'd_team_success'
      get 'd_team_sales'
      get 'd_executive'
      get 'd_competitors'
      get 'accounts_dashboard'
      get 'ad_sort_data/:sort' => 'reports#ad_sort_data', as: :ad_sort_data
      get 'ad_account_data/:id' => 'reports#ad_account_data', as: :ad_account_data
      get 'team_dashboard'
      get 'td_sort_data/:sort/:metric' => 'reports#td_sort_data', as: :td_sort_data
      get 'td_user_data/:id' => 'reports#td_user_data', as: :td_user_data
    end

    scope "extension", controller: :extension, as: 'extension' do
      get '/' => 'extension#index'
      get 'refer'
      get 'test'
      get 'share'
      get 'account'
      get 'company'
      get 'attachments'
      get 'download'
      # get 'alerts_tasks'
      get 'contacts'
      get 'settings'
      post 'save_settings'
      # get 'metrics'
      get 'no_account/:domain', to: 'extension#no_account', as: :no_account
      get 'private_domain'
      get 'project_error'
      # get 'salesforce'
      get 'custom_view'
      get 'salesforce_dashboard'
      post 'create_account'
      get 'dashboard'
      get 'dashboard_drilldown'
    end

    scope "tracking", controller: :tracking, as: 'tracking' do
      post 'create'
      get '/' => 'tracking#index'
      get 'list' => 'tracking#list'
      post 'toggle'
      get 'new_events'
      get 'new_event_objects' => 'tracking#new_event_objects'
      post 'seen'
    end

    resources :entity_fields_metadatum, controller: 'entity_fields_metadata', only: [:create, :update, :destroy] #for /settings/salesforce_fields/standard
    resources :custom_fields, only: [:update]
    resources :custom_fields_metadatum, only: [:create, :update, :destroy]  #for /settings/custom_fields
    resources :custom_lists, only: [:create, :update, :destroy]
    resources :custom_lists_metadata, only: [:create, :update, :destroy]  #for /settings/custom_lists
    resources :custom_configurations, only: [:update, :destroy]

    scope "onboarding", controller: :onboarding, as: 'onboarding' do
      get 'tutorial'
      get 'creating_clusters'
      get 'confirm_projects'
      get 'fill_in_info'
      get 'extension_tutorial'
    end
    post "users/:id/fill_in_info_update" => 'users#fill_in_info_update', :as => 'onboarding_fill_in_info_update'
  end

  # Cluster callback
  post 'onboarding/:user_id/create_clusters' => 'onboarding#create_clusters'

  devise_scope :user do # Unauthenticated user
    get '/auth/:provider/callback' => 'setting#basecamp'
    get "/user/omniauth/auth/:provider", to:  "omniauth_callbacks#user_omniauth_auth_helper", as: "user_omniauth_auth_helper"
    get "/users/auth/salesforcesandbox/callback" => 'omniauth_callbacks#salesforcesandbox'
  end

  scope "webhook", controller: :hooks, as: 'hooks' do
    post "jira"
    post "zendesk"
    post 'fullcontact_person'
    post 'fullcontact_company'
    post 'load_emails_since_yesterday'
    post 'load_events_since_yesterday'
    post 'stripe'
    get 'twilio_sms'
  end

  # twilio textwaittime
  post 'users/create_via_twilio'

  get "track/:user_email/:tracking_id/:gif" => 'tracking#view'
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def not_in_current_user_inbox(a)
		!(
			a.email_messages.map{|m| m.to.nil? ? [] : (m.to.map { |to| to.address }) }.flatten.include?(current_user.email) or
			a.email_messages.map{|m| m.from.map { |from| from.address } }.flatten.include?(current_user.email) or
			a.email_messages.map{|m| m.cc.nil? ? [] : (m.cc.map { |cc| cc.address }) }.flatten.include?(current_user.email)
		)
	end

  def last_msg_recipients(a)
    addresses = Set.new
    last_msg = a.email_messages.last
    from = last_msg.from || []
    to = last_msg.to || []
    cc = last_msg.cc || []
    addresses.merge((from + to + cc).map(&:address))
    (addresses - [current_user.email]).to_a * ","
  end

  def last_msg_subject(a)
    URI.escape("Re: " + a.title, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
  end

  def last_msg_body(a)
    last_msg = a.email_messages.last
    sent_date = Time.zone.at(last_msg.sentDate).strftime("%b %-d, %Y %I:%M %p")
    from_hash = last_msg.from.first
    from = ""
    from += " \"" + from_hash.personal + "\"" if from_hash.personal
    from += " <" + from_hash.address + ">" if from_hash.address
    body = last_msg.content && last_msg.content.respond_to?(:body) ? last_msg.content.body : last_msg.content.to_s 
    URI.escape("\n\nOn " + sent_date + "," + from + " wrote:\n\n" + body, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
  end

  def smart_email_body(message, users_available)
    body = message.content.nil? || message.content.is_a?(String) ? message.content : message.content.body
    if users_available
      message.temporalItems.reverse_each do |i|
        task = i.taskAnnotation
        body.insert(task.endOffset, "</a>").insert(task.beginOffset, "<a class=\"suggested-action\" data-message=\"#{message.messageId}\" data-due-date=\"#{Time.zone.at(i.resolvedDates.first).strftime('%Y-%m-%d')}\">")
      end if message.temporalItems
      simple_format(body, {}, sanitize: false)
    else
      simple_format(body)
    end
  end
end

app/views/projects/_activities_js.html.erb
<script>
$(document).ready(function() {
    $(".show-more-<%= a.backend_id %>").click(function() {
        $(".hidden-chat-message-<%= a.backend_id %>").each(function() {
            $(this).show();
        });
        $(".show-more-<%= a.backend_id %>").hide();
    });

    $(".comment-link-<%= a.id %>").click(function() {
        $(".form-<%= a.id %>").show();
    });
});
</script>

app/views/projects/_activities_tab.html.erb
<!-- Filter Section -->
<div class="row header-box projects-box white-bg">
  <%= render 'activities/filter', type: 'stream' unless @activities_by_month.blank? %>
</div>

<!-- Form -->
<div class="row header-box projects-box white-bg" style="margin-top: 1em">
  <%= render 'activities/form', :project => @project %>
</div>

<!-- Activities -->
<div id="newsfeed">
    <div class="row">
        <div class="col-lg-12">
            <div id="vertical-timeline" class="vertical-container light-timeline m-t">
                <%= render 'projects/timeline' %>
            </div>
        </div>
    </div>
</div>

<% if @activities_by_month.blank? %>
    <div class="p-m m-l m-t white-bg">
        <h4 class="text-center">You don't have any activities for this opportunity!</h4>
        <h4 class="text-center">To add a note for this opportunity, type something into the area above and click on the <a class="btn btn-sm sticky-bg" style="display:inline;">Post</a> button.</h4>
    </div>
<% end %>

<%= javascript_include_tag "notifications_table" %>

<script type="text/javascript">
  $(function () {
    $("#newsfeed-link").parent().addClass("active");
  });

  var popupWindowRef = null;
  var prevPopup = null;

  var openGmailComposePopup = function (strUrl, strTarget) {
    // var top = (window.screen.height/2) - (500/2);
    // var left = (window.screen.width/2) - (700/2);
    var strOptions = "width=700,height=500";
    if (popupWindowRef == null || popupWindowRef.closed) {
      popupWindowRef = window.open(strUrl, strTarget, strOptions);
    }
    else if (prevPopup != strUrl) {   
      popupWindowRef = window.open(strUrl, strTarget, strOptions);
      popupWindowRef.focus();
    }
    else {
      popupWindowRef.focus();
    }
    prevPopup = strUrl;
  }

  var bsTooltip = $().tooltip // Save bootstrap tooltip here so that it can be referenced after jQuery UI loads

  // Code for dismissable + one-open-at-a-time popovers
  $(document).on('click', function (e) {
    $('[data-toggle="popover"],[data-original-title]').each(function () {
      //the 'is' for buttons that trigger popups
      //the 'has' for icons within a button that triggers a popup
      if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
        (($(this).popover('hide').data('bs.popover')||{}).inState||{}).click = false  // fix for BS 3.3.6
      }
    });
  });

</script>

app/views/projects/_form.html.erb
  <%# Added Bootstrap classes, and help-block container for error messages %>  

  <span class="help-block" style="color:red"></span>
  <%= f.input :name, wrapper_html: { class: 'col-md-8'} %>
  <%= f.input :category, label: Project::MAPPABLE_FIELDS_META["category"], wrapper_html: { class: 'col-md-4'}, collection: @opportunity_types, selected: @project.category %>
  <% if @account.blank? %>
    <%= f.input :account_id, wrapper_html: { class: 'col-md-8'}, collection: @account_names, selected: @project.account.nil? ? @account_names[0] : @project.account.id %>
  <% else %>
    <%= f.input :account_id, as: :hidden, value: @account.id %>
  <% end %>
  
  <div class="col-md-4">
    <label class="select optional control-label" for="project_account_id">Open Collaboration &nbsp;&nbsp;<i data-toggle="tooltip" data-placement="top" title="" data-original-title="When enabled, everyone in your organization can view and collaborate." class="fa fa-question-circle"></i></label>
    <% if modal_id == 'edit_project_modal' %>
      <%= best_in_place @project, :is_public, :as => 'checkbox', collection: {false: raw("<input type=\"checkbox\" class=\"is_public-switch\" />"), true: raw("<input type=\"checkbox\" class=\"is_public-switch\" checked/>")}, :class => 'switch col-xs-3' %>
    <% else %>
      <div class="switch col-xs-3">
        <%= f.check_box :is_public, checked: true, class: 'is_public-switch' %>
      </div>
    <% end %>
  </div>

app/views/projects/_timeline.html.erb
<% @activities_by_month.each do |month, activities| %>
    <div class="vertical-timeline-month">
        <h3 class="p-xs m-l-n-sm gray-bg"><%= month %></h3>
    </div>
    
    <% activities.each do |a| %>
        <%= render 'activities/timeline_block', a: a %>
    <% end %>
<% end %>

<% if @activities_by_month.present? %>
  <% if @last_page %>
    <div class="timeline-end">
        <hr>
        <h3 class="text-mute-gray">You've reached the beginning.</h3>
    </div>
  <% else %>
    <div class="text-center">
      <button id="load-more" class="btn btn-primary m-b-lg">Read More <i class="fa fa-angle-double-down"></i></button>
    </div>
    <script type="text/javascript">
    $(function () {
      // Pagination/Infinite Scroll
      var page = <%= @page %>
      $('#load-more').click( function () {
        $(this).replaceWith('<i id="loading-more" class="fa fa-spinner fa-3x fa-pulse m-b-lg"></i>');
        page++;
        var url = '<%= project_path(@project) %>/more?';
        var params = ['page=' + page];
        var timeAxis = $('#time-filter-highcharts').highcharts().xAxis[0];
        if (timeAxis.min > timeAxis.dataMin || timeAxis.max < timeAxis.dataMax) {
          params.push("time=" +  timeAxis.min/1000 + "," + timeAxis.max/1000);
        } 
        if ($('.comment_category').val()) { 
          params.push("category=" + $('.comment_category').val()); 
        }
        if ($('.user_filter').val()) { 
          params.push("emails=" + $('.user_filter').val()); 
        }
        url += params.join('&');
        $.getScript(url);
      });
      var win = $(window);
      win.scroll(function () {
        if ($(document).height() - win.height() == win.scrollTop()) {
          $('#load-more').click();
        }
      });
    });
    </script>
  <% end %>
<% elsif params[:action] == "filter_timeline" %>
    <div class="timeline-end" style="height:0;">
        <hr>
        <h3 class="text-mute-gray">You've filtered everything out.</h3>
    </div>
<% end %>

app/views/projects/create.js.erb
window.location.replace("<%= project_path(@project) %>");

app/views/projects/destroy.js.erb
$('.<%= @project.id %>').fadeOut(400, function(){
    $('.<%= @project.id %>').remove();
});

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/filter_timeline.js.erb
$("#vertical-timeline").html('<%= escape_javascript(render "timeline") %>');
// reinitialize best_in_place/iCheck for dynamically added Smart Actions
jQuery(".best_in_place").best_in_place();
$('.i-checks').iCheck({checkboxClass: 'icheckbox_square-green'});

app/views/projects/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Opportunities</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= authenticated_root_path %>">Home</a>
            </li>
            <li class="active">
                <strong>Opportunities</strong>
            </li>
        </ol>
    </div>
    <% if current_user.pro? %>
    <div class="col-sm-2 col-sm-offset-6">
        <%= link_to '+ New Opportunity', '#new_project_modal', 'data-toggle' => 'modal', 'class' => 'btn btn-primary m-t-lg' %>
    </div>
    <% end %>
</div>

<div class="wrapper wrapper-content animated fadeInUp">
    <div class="row">
        <div class="col-md-12 filter-group">
          <div class="font-bold m-b-xs">Filter:</div>
          <form class="col-md-5" method='get' id='multiselect-filter-form' style='margin: 0 -20px 0 -15px'>
            <select id="type-filter" class="category_filter" style="width: 49%" multiple data-placeholder="  Select Type" title="Type">
              <option value="0"></option> <!-- no filter -->
              <% @opportunity_types.each do |k,v| %>
                <option value="<%= v %>" <% if params[:type].include? v %>selected<% end %> >
                  <%= v %>
                </option>
              <% end %>
            </select>
            <select id="owner-filter" class="category_filter" style="width: 49%" multiple data-placeholder="  Select Owner" title="Owner">
              <option value="0"></option> <!-- no filter -->
              <option value="<%= current_user.id %>" <% if params[:owner].include? current_user.id %> selected <% end %> >
                Me (<%= get_full_name(current_user) %>)
              </option>
              <% @owners.each do |u| %> <!-- diff between @owners vs users_reverse -->
                <% if u.id != current_user.id %>
                  <option value="<%= u.id %>" <% if params[:owner].include? u.id %> selected <% end %> >
                    <%= get_full_name(u) %>
                  </option>
                <% end %>
              <% end %>
              <option value="None" <% if params[:owner].include? "None" %> selected <% end %> >
                Unassigned
              </option>
            </select>
            <input type="submit" class="hidden"></input>
          </form>
          <select id="close-date-filter" class="category_filter col-sm-3" data-placeholder="Select Close Date" title="Close Date">
            <option value="Any"></option> <!-- no filter -->
            <optgroup label="By Close Date">
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:Open] %> ><%= Project::CLOSE_DATE_RANGE[:Open] %></option>
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:Closed] %> ><%= Project::CLOSE_DATE_RANGE[:Closed] %></option>
            </optgroup>
            <optgroup label="Quarter">
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:ThisQuarter] %> ><%= Project::CLOSE_DATE_RANGE[:ThisQuarter] %></option>
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:LastQuarter] %> ><%= Project::CLOSE_DATE_RANGE[:LastQuarter] %></option>
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:NextQuarter] %> ><%= Project::CLOSE_DATE_RANGE[:NextQuarter] %></option>
            </optgroup>
            <optgroup label="x-To-Date">
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:QTD] %> ><%= Project::CLOSE_DATE_RANGE[:QTD] %></option>
              <option <%= 'selected' if params[:close_date] == Project::CLOSE_DATE_RANGE[:YTD] %> ><%= Project::CLOSE_DATE_RANGE[:YTD] %></option>
            </optgroup>
          </select>
          <button style="border-radius: 5px; margin-left: 1em; padding: 5px 10px" onclick="setFilterParamsAndReloadPage();"><strong>Apply all filters&nbsp;</strong><i class="fa fa-filter" aria-hidden="true"></i></button>
          <button style="border-radius: 5px; margin-left: 1em; padding: 5px 10px" title="Reset filters" onclick="resetFilters();"><strong>Reset filters</strong></button>
        </div>

        <div class="col-md-4">
          <div class="ibox float-e-margins m-b-none m-t">
            <div class='ibox-title'>
              <h5>Deals by Forecast <small>(Click bar to filter)</small></h5>
            </div>
            <div id="forecast-chart" class="ibox-content forecast-chart" style="height:150px;padding-bottom:0"></div>
          </div>
        </div>

        <div class="col-md-8">
          <div class="ibox float-e-margins m-b-none m-t">
            <div class='ibox-title'>
              <h5>Deals by Stage <small>(Click bar to filter)</small></h5>
            </div>
            <div id="stage-chart" class="ibox-content stage-chart" style="height:150px;padding-bottom:0"></div>
          </div>
        </div>
    </div>

    <% if current_user.admin? %>
    <div class="row" style="margin-top: 1em">
        <div class="col-md-12 bulk-group">
            <div class="font-bold m-b-xs">Bulk Operation:</div>
            <button type="button" class="btn btn-sm btn-white bulk-action" id="bulk-delete" disabled> Delete </button>
            <select class="bulk-action col-sm-3" data-placeholder="Change Category" id="bulk-category" disabled>
              <option value="0"></option>
              <% @opportunity_types.each do |k,v| %>
              <option value="<%= v %>" ><%= v %></option>
              <% end %>
            </select>
            <select class="bulk-action col-sm-3" data-placeholder="Change Owner" id="bulk-owner" disabled>
              <option value="0"></option>
              <% @owners.each do |u| %>
              <option value="<%= u.id %>" ><%= get_full_name(u) %></option>
              <% end %>
            </select>
            <select class="bulk-action col-sm-3" data-placeholder="Change Status" id="bulk-status" disabled>
              <option value="0"></option>
              <% Project::STATUS.each do |s| %>
              <option value="<%= s %>" ><%= s %></option>
              <% end %>
            </select>
        </div>
    </div>
    <% end %>

    <div class="row">
        <div class="col-sm-12 m-t-md">
          <!-- no projects snippet -->
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <table class="table table-hover display nowrap" id="projects-table" cellspacing="0" width="100%" data-source="<%= projects_path(format: :json) %>">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th><%= Project::MAPPABLE_FIELDS_META["stage"] %></th>
                                    <th><%= Project::MAPPABLE_FIELDS_META["amount"] %></th>
                                    <th><%= Project::MAPPABLE_FIELDS_META["forecast"] %></th>
                                    <th>Owner</th>
                                    <th></th>
                                    <th>Next Steps</th>
                                    <th>Next Meeting</th>
                                    <th>Close Date</th>
                                    <th>Alerts & Tasks</th>
                                    <th>Last 7d Activity</th>
                                    <th>Days Inactive</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            <!-- projects loop -->
                            </tbody>
                        </table>
                    </div>
                </div>
<!-- end projects snippet -->
        </div>
    </div>
</div>
<%= render 'projects/modal', modal_id: 'new_project_modal', remote: true %>

<script type="text/javascript" charset="utf-8">
$(function () {
  $('#forecast-chart').highcharts({
    chart: {
      type: 'column'
    },
    title: {
      text: ''
    },
    credits: {
      enabled: false
    },
    xAxis: {
      crosshair: true,
      labels: {
        style: {
          fontSize: '9px'
        }
      }
    },
    yAxis: {
      min: 0,
      title: {
        text: ''
      },
      labels: {
        enabled: false
      },
      stackLabels: {
        enabled: true,
        formatter: function () {
          return "$"+large_number_to_human_signif_digits(this.total);
        },
        style: {
          color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
        }
      }
    },
    tooltip: {
      enabled: true,
      formatter: function () {
        return '$' + large_number_to_human_signif_digits(this.total) + ' in ' + this.x;
      }
    },
    legend: {
      enabled: false
    },
    plotOptions: {
      column: {
        stacking: 'normal',
        pointPadding: 0.2,
        borderWidth: 0,
        dataLabels: {
          enabled: false,
          format: '${y}',
          style: {
            color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
          }
        }
      },
      series: {
        pointPadding: 0.1,
        groupPadding: 0,
        borderWidth: 0,
        point: {
          events: {
            click: function () {
              this.select(!this.selected, true);
            }
          }
        }
      }
    }
  });

  $('#stage-chart').highcharts({
    chart: {
      type: 'column'
    },
    title: {
      text: ''
    },
    credits: {
      enabled: false
    },
    xAxis: {
      crosshair: true,
      labels: {
        style: {
          fontSize: '9px'
        }
      }
    },
    yAxis: {
      min: 0,
      title: {
        text: ''
      },
      labels: {
        enabled: false
      },
      stackLabels: {
        enabled: true,
        formatter: function () {
          //return Highcharts.numberFormat(this.total, 0, null, "");
          return "$"+large_number_to_human_signif_digits(this.total);
        },
        style: {
          color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
        }
      }
    },
    tooltip: {
      enabled: true,
      formatter: function () {
        return '$' + large_number_to_human_signif_digits(this.total) + ' in ' + this.x;
      }
    },
    legend: {
      enabled: false
    },
    series: [{

    }],
    plotOptions: {
      column: {
        stacking: 'normal',
        pointPadding: 0.2,
        borderWidth: 0,
        dataLabels: {
          format: '${y}',
          style: {
            color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
          }
        }
      },
      series: {
        pointPadding: 0.1,
        groupPadding: 0.1,
        borderWidth: 0,
        point: {
          events: {
            click: function () {
              this.select(!this.selected, true);
            }
          }
        }
      }
    }
  });

  // < %= render partial: 'reports/stage_chart.js' %>
  <%= render partial: 'reports/accounts_dashboard_top.js' %>

})
</script>

app/views/projects/more_timeline.js.erb
$('#loading-more').remove();
$(window).off();
// Pagination event handlers reloaded when timeline is rendered
$("#vertical-timeline").append('<%= escape_javascript(render "timeline") %>');
// reinitialize best_in_place/iCheck for dynamically added Smart Actions
jQuery(".best_in_place").best_in_place();
$('.i-checks').iCheck({checkboxClass: 'icheckbox_square-green'});

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/update.js.erb
<% if @ns_updated %>
$('#vertical-timeline').prepend('<%= escape_javascript(render "activities/timeline_block", a: @activity) %>');
$('.vertical-timeline-block').first().hide().show("blind", {direction: "up"}, 1000);
$('#next-steps-updated-at').text('Updated just now');
<% else %>
window.location.replace("<%= project_path(@project) %>");
<% end %>