config/routes.rb
Longclaw::Application.routes.draw do
  unauthenticated do
    get "extension/refer" => "onboarding#refer"
    get "extension" => "extension#new"
    get "extension/account" => "extension#new"
    get "extension/custom_view" => "extension#new"
  end

  resources :plans
  get 'home/access_denied'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "sessions" }
  # You can have the root of your site routed with "root"

  authenticate :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "home#index", :as => "authenticated_root"

    resources :accounts
    post "/account_bulk" => 'accounts#bulk'
    # get "/update_salesforce" => 'accounts#set_salesforce_account'

    resources :contacts, only: [:create, :update, :destroy]
    resources :projects do
      member do
        get "tasks" => 'projects#tasks_tab'
        get "arg" => 'projects#arg_tab'
        get "filter" => 'projects#filter_timeline'
        get "more" => 'projects#more_timeline'
        get "network_map"
        get "/:time/network_map" => 'projects#network_map'
        get "lookup"
        post "refresh"
      end
      resources :project_subscribers, param: :user_id, only: [:destroy, :create]
      post "project_subscribers/create_all"
    end
    post "/project_bulk" => 'projects#bulk'
    delete "project_subscribers/destroy_other"

    resources :project_members
    resources :users
    post 'user/create' => 'users#create'
    get 'user/me' => 'users#me'
    get 'plans/upgrade' => 'plans#upgrade'
    #resources :plans

    resources :notifications, only: [:index, :update, :create] do
      member do
        get "update_is_complete" => 'notifications#update_is_complete'
        get "download" => 'notifications#download_attachment'
        get "message" => 'notifications#show_message'
      end
      collection do
        post "create_from_suggestion"
      end
    end

    resources :salesforce, only: [:index]
    get "salesforce/disconnect/:id" => 'salesforce#disconnect', as: "salesforce_disconnect"
    post "/link_salesforce_account" => 'salesforce#link_salesforce_account'
    post "/link_salesforce_opportunity" => 'salesforce#link_salesforce_opportunity'
    post "/salesforce/import/:entity_type" => 'salesforce#import_salesforce'
    post "/salesforce/sync" => 'salesforce#sync_salesforce'
    # post "/salesforce_fields_refresh" => 'salesforce#refresh_fields'
    delete "/delete_salesforce_account/:id" => 'salesforce#remove_account_link'
    delete "/delete_salesforce_opportunity/:id" => 'salesforce#remove_opportunity_link'
    post "/salesforce/update_all/:entity_type/:id" => 'salesforce#update_all_salesforce'

    scope "settings", controller: :settings, as: 'settings' do
      get "/" => "settings#index"
      get "users"
      get "alerts"
      post "alerts" => "settings#create_for_alerts"
      get "custom_fields"
      get "custom_lists"
      get "custom_list/:id" => 'settings#custom_list_show'
      get "salesforce_accounts"
      get "salesforce_opportunities"
      get "salesforce_activities"
      get "salesforce_fields/:type" => "settings#salesforce_fields", as: "salesforce_fields"
      get "super_user"
      post "update_user_org" => "settings#organization_jump"
      get "user_analytics"
      post "invite_user/:user_id" => 'settings#invite_user'
    end


    get "/delete_single_activity/:id" => 'activities#destroy'

    resources :activities, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy], shallow: true
      member do
        get 'message' => 'activities#show_message'
      end
    end
    
    resources :organizations


    scope "search", controller: :search, as: 'search' do
      # get "results"
      get "autocomplete_project_name"
      get "autocomplete_contacts"
      get "autocomplete_project_subs"
      get "autocomplete_project_member"
      get "autocomplete_salesforce_account_name"
      get "autocomplete_salesforce_opportunity_name"
    end
    
    scope "reports", controller: :reports, as: 'reports' do
      get 'd_account_success'
      get 'd_account_sales'
      get 'd_team_success'
      get 'd_team_sales'
      get 'd_executive'
      get 'd_competitors'
      get 'accounts_dashboard'
      get 'ad_sort_data/:sort' => 'reports#ad_sort_data', as: :ad_sort_data
      get 'ad_account_data/:id' => 'reports#ad_account_data', as: :ad_account_data
      get 'team_dashboard'
      get 'td_sort_data/:sort/:metric' => 'reports#td_sort_data', as: :td_sort_data
      get 'td_user_data/:id' => 'reports#td_user_data', as: :td_user_data
    end

    scope "extension", controller: :extension, as: 'extension' do
      get '/' => 'extension#index'
      get 'refer'
      get 'test'
      get 'share'
      get 'account'
      get 'company'
      get 'attachments'
      get 'download'
      # get 'alerts_tasks'
      get 'contacts'
      get 'settings'
      post 'save_settings'
      # get 'metrics'
      get 'no_account/:domain', to: 'extension#no_account', as: :no_account
      get 'private_domain'
      get 'project_error'
      # get 'salesforce'
      get 'custom_view'
      get 'salesforce_dashboard'
      post 'create_account'
      get 'dashboard'
      get 'dashboard_drilldown'
    end

    scope "tracking", controller: :tracking, as: 'tracking' do
      post 'create'
      get '/' => 'tracking#index'
      get 'list' => 'tracking#list'
      post 'toggle'
      get 'new_events'
      get 'new_event_objects' => 'tracking#new_event_objects'
      post 'seen'
    end

    resources :entity_fields_metadatum, controller: 'entity_fields_metadata', only: [:create, :update, :destroy] #for /settings/salesforce_fields/standard
    resources :custom_fields, only: [:update]
    resources :custom_fields_metadatum, only: [:create, :update, :destroy]  #for /settings/custom_fields
    resources :custom_lists, only: [:create, :update, :destroy]
    resources :custom_lists_metadata, only: [:create, :update, :destroy]  #for /settings/custom_lists
    resources :custom_configurations, only: [:update, :destroy]

    scope "onboarding", controller: :onboarding, as: 'onboarding' do
      get 'tutorial'
      get 'creating_clusters'
      get 'confirm_projects'
      get 'fill_in_info'
      get 'extension_tutorial'
    end
    post "users/:id/fill_in_info_update" => 'users#fill_in_info_update', :as => 'onboarding_fill_in_info_update'
  end

  # Cluster callback
  post 'onboarding/:user_id/create_clusters' => 'onboarding#create_clusters'

  devise_scope :user do # Unauthenticated user
    get '/auth/:provider/callback' => 'setting#basecamp'
    get "/user/omniauth/auth/:provider", to:  "omniauth_callbacks#user_omniauth_auth_helper", as: "user_omniauth_auth_helper"
    get "/users/auth/salesforcesandbox/callback" => 'omniauth_callbacks#salesforcesandbox'
  end

  scope "webhook", controller: :hooks, as: 'hooks' do
    post "jira"
    post "zendesk"
    post 'fullcontact_person'
    post 'fullcontact_company'
    post 'load_emails_since_yesterday'
    post 'load_events_since_yesterday'
    post 'stripe'
    get 'twilio_sms'
  end

  # twilio textwaittime
  post 'users/create_via_twilio'

  get "track/:user_email/:tracking_id/:gif" => 'tracking#view'
end

app/controllers/onboarding_controller.rb
require 'net/http'
require "erb"
include ERB::Util

class OnboardingController < ApplicationController
	layout 'empty', except: ['tutorial', 'extension_tutorial']
	# layout false, only: ['tutorial', 'extension_tutorial']

  def fill_in_info
    start_new_user
  end

  def refer
    @referral = true
    puts params[:ref]
    @referral_user = PlansService.referral_user(params[:ref])
    render 'onboarding/extension_tutorial', layout: false
  end

  def extension_tutorial
    render layout: false
    start_new_user(Utils::ONBOARDING[:onboarded])
  end

	def tutorial
    render layout: false
		# change user onboarding status
		if current_user.mark_private == true # Skip this step if you're VP level or above (all 1-1 e-mails are private)
			current_user.update_attributes(onboarding_step: Utils::ONBOARDING[:onboarded])
		else
			current_user.update_attributes(onboarding_step: Utils::ONBOARDING[:confirm_projects]) if current_user.onboarding_step == Utils::ONBOARDING[:tutorial]
		end
  end

  # Show the user the onboarding "Processing e-mails" in-progress page.
	def creating_clusters
		if current_user.onboarding_step == Utils::ONBOARDING[:confirm_projects] and !current_user.cluster_create_date.nil?
			redirect_to onboarding_confirm_projects_path
		elsif current_user.onboarding_step == Utils::ONBOARDING[:onboarded]
			redirect_to authenticated_root_path
		end
	end

	# Allow user to confirm processed clusters (in the form of opportunities/projects)
	def confirm_projects
		return_vals = User.confirm_projects_for_user(current_user)

		redirect_to authenticated_root_path and return if return_vals == -1 

    @overlapping_projects = return_vals[:overlapping_projects]
    @new_projects = return_vals[:new_projects]
    @same_projects = return_vals[:same_projects]
    @account_types = return_vals[:account_types]
    @project_last_email_date = return_vals[:project_last_email_date]
	end

	#########################################################################
	# Callback method from backend during onboarding process to create clusters for a particular user 
	#
	# Example: 	 curl -H "Content-Type: application/json" --data @/Users/willcheung/Downloads/contextsmith-json-3.txt http://localhost:3000/onboarding/64eb67f6-3ed1-4678-84ab-618d348cdf3a/create_clusters.json
	# Example 2: http://64.201.248.178/:8888/newsfeed/cluster?email=indifferenzetester@gmail.com&token=test&max=300&before=1408695712&in_domain=comprehend.com&callback=http://24.130.10.244:3000/onboarding/64eb67f6-3ed1-4678-84ab-618d348cdf3a/create_clusters.json
	#
	#########################################################################

	def create_clusters
    CreateClustersJob.perform_later(params)

    # puts 'Responding to Oathkeeper...'
    respond_to do |format|
      format.json { render json: 'Create clusters kicked off for ' + params[:user_id], status: :accepted }
    end
    # puts 'Response sent!'
  end

  private

  def start_new_user(step=Utils::ONBOARDING[:tutorial])
    # change user onboarding status and cluster_create_date becomes join date
    if current_user.onboarding_step == Utils::ONBOARDING[:fill_in_info]
      current_user.update(onboarding_step: step)
      if Rails.env.production?
        list_id = ENV['mailchimp_email_list_id']
        # Using MailChimp for email automation. User's domain will be sent to ContextSmith Trial Newsletter
        uri = URI('https://us13.api.mailchimp.com/3.0/lists/' + list_id + '/members/')
        res = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
          req = Net::HTTP::Post.new(uri)
          req['Content-Type'] = 'application/json'
          req.basic_auth 'anystring', ENV["mailchimp_api_key"]
          json_data = {'email_address' => current_user.email, 'status' => 'subscribed', "merge_fields" => {"FNAME"=>"#{current_user.first_name}","LNAME" => "#{current_user.last_name}"} }.to_json
          req.body = json_data
          response = http.request(req) # Net::HTTPResponse object
        end
        # MailChimp API call takes a few minutes before contact is added to the mailchimp list
      end
      # Alert the CS team when a new user has signed up to our platform! Need to revise once this becomes too noisy
      UserMailer.update_cs_team(current_user).deliver_now
    end
  end
end

app/views/onboarding/creating_clusters.html.erb
<div id="loader" class="overlay-loader">
	<div class="loader-background color-flip"></div>
	<img class="loader-icon spinning-cog" src="<%= image_path('cogs/cog20.svg') %>" data-cog="cog20">

  <div class="credits">
    <h1>Hang tight!</h1>
    <h1> We're still processing your e-mails and finding insights.</h1><br>
    <h3>This may take a few more minutes. We'll send you an e-mail to <span style="color:#fff;font-weight:500"><%= current_user.email %></span> to let you know when we're done.</h3>
  	<h3>You may close this window now.</h3>
  </div>
</div>

<script>
window.onload = setupRefresh;

function setupRefresh() {
  setTimeout("refreshPage();", 10000);
}
function refreshPage() {
   window.location = location.href;
}
</script>

app/views/onboarding/extension_tutorial.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Getting Started with ContextSmith</title>

  <!-- Bootstrap -->
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <link rel="stylesheet" type="text/css" href="/assets/stylesheets/style.css">
  <link rel="stylesheet" type="text/css" href="/assets/stylesheets/animate.min.css">


  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <style>
    .bs-wizard {margin-top: 40px;}

    /*Form Wizard*/
    .bs-wizard {border-bottom: solid 1px #e0e0e0; padding: 0 0 10px 0;}
    .bs-wizard > .bs-wizard-step {padding: 0; position: relative;}
    .bs-wizard > .bs-wizard-step + .bs-wizard-step {}
    .bs-wizard > .bs-wizard-step .bs-wizard-stepnum {color: #595959; font-size: 13px; margin-bottom: 5px;}
    .bs-wizard > .bs-wizard-step .bs-wizard-info {color: #999; font-size: 12px;}
    .bs-wizard > .bs-wizard-step > .bs-wizard-dot {position: absolute; width: 30px; height: 30px; display: block; background: #77afd7; top: 45px; left: 50%; margin-top: -15px; margin-left: -15px; border-radius: 50%;} 
    .bs-wizard > .bs-wizard-step > .bs-wizard-dot:after {content: ' '; width: 14px; height: 14px; background: #3c6bc5; border-radius: 50px; position: absolute; top: 8px; left: 8px; } 
    .bs-wizard > .bs-wizard-step > .progress {position: relative; border-radius: 0px; height: 8px; box-shadow: none; margin: 20px 0;}
    .bs-wizard > .bs-wizard-step > .progress > .progress-bar {width:0px; box-shadow: none; background: #77afd7;}
    .bs-wizard > .bs-wizard-step.complete > .progress > .progress-bar {width:100%;}
    .bs-wizard > .bs-wizard-step.active > .progress > .progress-bar {width:50%;}
    .bs-wizard > .bs-wizard-step:first-child.active > .progress > .progress-bar {width:0%;}
    .bs-wizard > .bs-wizard-step:last-child.active > .progress > .progress-bar {width: 100%;}
    .bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot {background-color: #f5f5f5;}
    .bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot:after {opacity: 0;}
    .bs-wizard > .bs-wizard-step:first-child  > .progress {left: 50%; width: 50%;}
    .bs-wizard > .bs-wizard-step:last-child  > .progress {width: 50%;}
    .bs-wizard > .bs-wizard-step.disabled a.bs-wizard-dot{ pointer-events: none; }
    /*END Form Wizard*/

    #Second_section, #Third_section, #Fourth_section {
      padding: 15px 0;
    }

    .free {
      color: #EEE;
    }

    @media only screen and (min-width: 1024px) {
      .img-responsive {
        width: 1024px;
      }
    }

  </style>
</head>
<body>
<!-- header -->
<header>
  <div class="container">
    <div class="rowsample">
      <div class="col-md-6 col-xs-6 col-sm-6">
        <img id="logo" src="/assets/logo-white.png">
      </div>
      <div class="col-md-6 col-xs-6 col-sm-6">
        <!--<button class="btn btn-default first-btn">Skip Tutorial</button>-->
      </div>
    </div>
  </div>
</header>
<!-- header-end -->
<!-- first_section -->
<section id="first_section" class="extension-tutorial">
  <div class="container">
    <div class="rowsample" style="margin-bottom: 50px;margin-top:50px;">
      <% if current_user %>
          <h4>Thank you for signing up, <%= current_user.first_name.present? ? current_user.first_name : "my friend" %></h4>
      <% elsif @referral_user %>
          <h2><%= @referral_user.first_name.present? ? @referral_user.first_name : @referral_user.email %> would like you to sign up for ContextSmith</h2>
      <% else %>
      Welcome to the free ContextSmith Google Mail add-on!
      <% end %>
      <h4>Get to know ContextSmith in 3 simple steps.</h4>
    </div>

      <div class="container">
            <div class="row bs-wizard" style="border-bottom:0;margin-bottom:100px;">
                
                <div class="col-xs-4 bs-wizard-step complete">
                  <div class="text-center bs-wizard-stepnum">1. COMPOSE EMAIL</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a data-scroll href="#Second_section" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center"></div>
                </div>
                
                <div class="col-xs-4 bs-wizard-step complete"><!-- complete -->
                  <div class="text-center bs-wizard-stepnum">2. TRACK EMAIL OPEN</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a data-scroll href="#Third_section" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center"></div>
                </div>
                
                <div class="col-xs-4 bs-wizard-step active"><!-- complete -->
                  <div class="text-center bs-wizard-stepnum">3. SEE PROFILE</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a data-scroll href="#Fourth_section" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center"></div>
                </div>
          </div>     
      </div>

      <a data-scroll href="#Second_section"><img class="down-arrow display-inline" src="/assets/images/tutorial/DownIcon.png"></a>
    </div>
  </div>
</section>

<!-- first_section -->
<section id="Second_section" class="extension-tutorial">
  <div class="container">
    <div class="rowsample">
      <h3>
        <span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i>
          <strong class="fa-stack-1x circled-number" style="color: #2578B6;">1</strong>
        </span>
        Compose or reply to any email - now with superpower tracking.
      </h3>
      <img class="img-responsive display-inline" src="/assets/images/tutorial/step1.png" alt="Compose Track Outgoing">
      <br>
      <a data-scroll href="#Third_section"><img class="down-arrow display-inline" src="/assets/images/tutorial/DownIcon2.png"></a>
    </div>
  </div>
</section>
<!-- Second_section -->
<section id="Third_section" class="extension-tutorial">
  <div class="container">
    <div class="rowsample">
      <h3><span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i>
          <strong class="fa-stack-1x circled-number" style="color: white">2</strong>
        </span>
        See which emails were read. Know when it was read and on what device.</h3>
      <img class="img-responsive display-inline" src="/assets/images/tutorial/step2.png" alt="View Tracked Emails">
      <br>
      <a data-scroll href="#Fourth_section"><img class="down-arrow display-inline" src="/assets/images/tutorial/DownIcon.png"></a>
    </div>
  </div>
</section>
<!-- Third_section -->
<section id="Fourth_section" class="extension-tutorial">
  <div class="container">
    <div class="rowsample">
      <h3><span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i>
          <strong class="fa-stack-1x circled-number" style="color: #2578B6;">3</strong>
        </span>
        Click on any email to see contact profiles in Gmail sidebar.</h3>
      <img class="img-responsive display-inline" src="/assets/images/tutorial/step3.png" alt="See Contact Information">
      <div class="text-center">
        <% if current_user %>
            <a href="<%= extension_path(login: true) %>"><button class="btn btn-default first-btn">Get Started</button></a>
        <% else %>
            <a href="<%= user_omniauth_authorize_path(:google_oauth2, extension: true, ref: params[:ref]) %>">
              <img class="google-oauth-btn" src="/assets/images/google_signin_buttons/web/2x/btn_google_signin_dark_normal_web@2x.png" style="margin-top: 1em" title="Sign up using Google"></a>
            <br><span class="free">It's free!</span>
            <p class="oauth" style="font-size:10px;margin-top:5em;">By clicking this button, you agree to our
              <br><a href="https://www.contextsmith.com/terms/" style="color: #eee;" target="_blank">Terms of Service</a>.</p>

        <% end %>
      </div>

    </div>
  </div>
</section>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" %>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" %>
<script src="/assets/javascripts/smooth-scroll.min.js"></script>
<script src="/assets/javascripts/wow.min.js"></script>
<script>
  smoothScroll.init({speed: 500, easing: 'easeInOutCubic', updateURL: false});
  wow = new WOW({mobile:true,})
  wow.init();

</script>

<!-- Google Analytics -->
<% if ENV["RAILS_ENV"] == 'production' %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-68686500-2', 'auto');
      ga('send', 'pageview');
    </script>
<% end %>
</body>
</html>

app/views/onboarding/fill_in_info.html.erb
<div class="text-center loginscreen animated fill_in_info">
  <div style="margin: 100px 0;">
      <div class="ibox-content middle-box" style="max-width: 600px;">
          <h1 class="logo-name oauth">Almost there...</h1>
          <p class="oauth" style="margin-bottom:40px;">We just need a few details to get you started.</p>

          <div class="row">
        		<%= simple_form_for current_user, url: onboarding_fill_in_info_update_path(current_user), method: 'post' do |f| %>

              <%# Added Bootstrap classes, and help-block container for error messages %> 
              <%= f.input :mark_private,  as: :radio_buttons, label: 'Are you a senior executive (Director or above)?', label_html: { style: 'font-size:22px;font-weight:400;color:#999;margin-right:20px;display:block' } %>
              <%= f.input :title, wrapper_html: { class: 'col-md-12 m-b-lg'}, input_html: { class: 'text-center', style: 'font-size:24px;height:50px' }, label: false, placeholder: "What's your title?" %>
              <%= f.input :department, wrapper_html: { class: 'col-md-12 m-b-lg'}, input_html: { class: 'text-center', style: 'font-size:24px;height:50px' }, label: false, placeholder: "Which department?" %>     
              
              <%# Added Bootstrap classes %>
              <%= f.button :submit, 'Next →', class: 'btn-primary btn-lg form-group text-center' %>

            <% end %>
          </div>
      </div>

  </div>
</div>

app/views/onboarding/four.html.erb
Step four.

app/views/onboarding/intro_accounts.html.erb
Step four.

app/views/onboarding/intro_overall.html.erb
Some image here.

app/views/onboarding/one.html.erb
Some image here.

app/views/onboarding/three.html.erb
Step three

app/views/onboarding/two.html.erb
Step 2