config/routes.rb
Longclaw::Application.routes.draw do
  unauthenticated do
    get "extension/refer" => "onboarding#refer"
    get "extension" => "extension#new"
    get "extension/account" => "extension#new"
    get "extension/custom_view" => "extension#new"
  end

  resources :plans
  get 'home/access_denied'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "sessions" }
  # You can have the root of your site routed with "root"

  authenticate :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "home#index", :as => "authenticated_root"

    resources :accounts
    post "/account_bulk" => 'accounts#bulk'
    # get "/update_salesforce" => 'accounts#set_salesforce_account'

    resources :contacts, only: [:create, :update, :destroy]
    resources :projects do
      member do
        get "tasks" => 'projects#tasks_tab'
        get "arg" => 'projects#arg_tab'
        get "filter" => 'projects#filter_timeline'
        get "more" => 'projects#more_timeline'
        get "network_map"
        get "/:time/network_map" => 'projects#network_map'
        get "lookup"
        post "refresh"
      end
      resources :project_subscribers, param: :user_id, only: [:destroy, :create]
      post "project_subscribers/create_all"
    end
    post "/project_bulk" => 'projects#bulk'
    delete "project_subscribers/destroy_other"

    resources :project_members
    resources :users
    post 'user/create' => 'users#create'
    get 'user/me' => 'users#me'
    get 'plans/upgrade' => 'plans#upgrade'
    #resources :plans

    resources :notifications, only: [:index, :update, :create] do
      member do
        get "update_is_complete" => 'notifications#update_is_complete'
        get "download" => 'notifications#download_attachment'
        get "message" => 'notifications#show_message'
      end
      collection do
        post "create_from_suggestion"
      end
    end

    resources :salesforce, only: [:index]
    get "salesforce/disconnect/:id" => 'salesforce#disconnect', as: "salesforce_disconnect"
    post "/link_salesforce_account" => 'salesforce#link_salesforce_account'
    post "/link_salesforce_opportunity" => 'salesforce#link_salesforce_opportunity'
    post "/salesforce/import/:entity_type" => 'salesforce#import_salesforce'
    post "/salesforce/sync" => 'salesforce#sync_salesforce'
    # post "/salesforce_fields_refresh" => 'salesforce#refresh_fields'
    delete "/delete_salesforce_account/:id" => 'salesforce#remove_account_link'
    delete "/delete_salesforce_opportunity/:id" => 'salesforce#remove_opportunity_link'
    post "/salesforce/update_all/:entity_type/:id" => 'salesforce#update_all_salesforce'

    scope "settings", controller: :settings, as: 'settings' do
      get "/" => "settings#index"
      get "users"
      get "alerts"
      post "alerts" => "settings#create_for_alerts"
      get "custom_fields"
      get "custom_lists"
      get "custom_list/:id" => 'settings#custom_list_show'
      get "salesforce_accounts"
      get "salesforce_opportunities"
      get "salesforce_activities"
      get "salesforce_fields/:type" => "settings#salesforce_fields", as: "salesforce_fields"
      get "super_user"
      post "update_user_org" => "settings#organization_jump"
      get "user_analytics"
      post "invite_user/:user_id" => 'settings#invite_user'
    end


    get "/delete_single_activity/:id" => 'activities#destroy'

    resources :activities, only: [:create, :update, :destroy] do
      resources :comments, only: [:create, :update, :destroy], shallow: true
      member do
        get 'message' => 'activities#show_message'
      end
    end
    
    resources :organizations


    scope "search", controller: :search, as: 'search' do
      # get "results"
      get "autocomplete_project_name"
      get "autocomplete_contacts"
      get "autocomplete_project_subs"
      get "autocomplete_project_member"
      get "autocomplete_salesforce_account_name"
      get "autocomplete_salesforce_opportunity_name"
    end
    
    scope "reports", controller: :reports, as: 'reports' do
      get 'd_account_success'
      get 'd_account_sales'
      get 'd_team_success'
      get 'd_team_sales'
      get 'd_executive'
      get 'd_competitors'
      get 'accounts_dashboard'
      get 'ad_sort_data/:sort' => 'reports#ad_sort_data', as: :ad_sort_data
      get 'ad_account_data/:id' => 'reports#ad_account_data', as: :ad_account_data
      get 'team_dashboard'
      get 'td_sort_data/:sort/:metric' => 'reports#td_sort_data', as: :td_sort_data
      get 'td_user_data/:id' => 'reports#td_user_data', as: :td_user_data
    end

    scope "extension", controller: :extension, as: 'extension' do
      get '/' => 'extension#index'
      get 'refer'
      get 'test'
      get 'share'
      get 'account'
      get 'company'
      get 'attachments'
      get 'download'
      # get 'alerts_tasks'
      get 'contacts'
      get 'settings'
      post 'save_settings'
      # get 'metrics'
      get 'no_account/:domain', to: 'extension#no_account', as: :no_account
      get 'private_domain'
      get 'project_error'
      # get 'salesforce'
      get 'custom_view'
      get 'salesforce_dashboard'
      post 'create_account'
      get 'dashboard'
      get 'dashboard_drilldown'
    end

    scope "tracking", controller: :tracking, as: 'tracking' do
      post 'create'
      get '/' => 'tracking#index'
      get 'list' => 'tracking#list'
      post 'toggle'
      get 'new_events'
      get 'new_event_objects' => 'tracking#new_event_objects'
      post 'seen'
    end

    resources :entity_fields_metadatum, controller: 'entity_fields_metadata', only: [:create, :update, :destroy] #for /settings/salesforce_fields/standard
    resources :custom_fields, only: [:update]
    resources :custom_fields_metadatum, only: [:create, :update, :destroy]  #for /settings/custom_fields
    resources :custom_lists, only: [:create, :update, :destroy]
    resources :custom_lists_metadata, only: [:create, :update, :destroy]  #for /settings/custom_lists
    resources :custom_configurations, only: [:update, :destroy]

    scope "onboarding", controller: :onboarding, as: 'onboarding' do
      get 'tutorial'
      get 'creating_clusters'
      get 'confirm_projects'
      get 'fill_in_info'
      get 'extension_tutorial'
    end
    post "users/:id/fill_in_info_update" => 'users#fill_in_info_update', :as => 'onboarding_fill_in_info_update'
  end

  # Cluster callback
  post 'onboarding/:user_id/create_clusters' => 'onboarding#create_clusters'

  devise_scope :user do # Unauthenticated user
    get '/auth/:provider/callback' => 'setting#basecamp'
    get "/user/omniauth/auth/:provider", to:  "omniauth_callbacks#user_omniauth_auth_helper", as: "user_omniauth_auth_helper"
    get "/users/auth/salesforcesandbox/callback" => 'omniauth_callbacks#salesforcesandbox'
  end

  scope "webhook", controller: :hooks, as: 'hooks' do
    post "jira"
    post "zendesk"
    post 'fullcontact_person'
    post 'fullcontact_company'
    post 'load_emails_since_yesterday'
    post 'load_events_since_yesterday'
    post 'stripe'
    get 'twilio_sms'
  end

  # twilio textwaittime
  post 'users/create_via_twilio'

  get "track/:user_email/:tracking_id/:gif" => 'tracking#view'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :get_current_org_users, only: [:accounts_dashboard, :ad_sort_data]
  before_action :ad_filter_state, only: [:accounts_dashboard, :ad_sort_data]
  before_action :td_filter_state, only: [:team_dashboard, :td_sort_data]

  ACCOUNT_DASHBOARD_METRIC = { :activities_last14d => "Activities (Last 14d)", :days_inactive => "Days Inactive", :open_alerts_and_tasks => "Open Alerts & Tasks", :overdue_tasks => "Total Overdue Tasks", :deal_size => "Deal Size", :days_to_close => "Days to Close"} # Removed: :risk_score => "Risk Score"
  TEAM_DASHBOARD_METRIC = { :activities_last14d => "Activities (Last 14d)", :time_spent_last14d => "Time Spent (Last 14d)", :closed_won => "Closed Won", :win_rate => "Win Rate", :opportunities => "Opportunities", :closed_alerts_and_tasks_last14d => "Closed Alerts & Tasks (Last 14d)", :open_alerts_and_tasks => "Open Alerts & Tasks" } # Removed: :new_alerts_and_tasks_last_14d

  # "accounts_dashboard" is actually referring to opportunities, AKA projects
  def accounts_dashboard
    custom_lists = current_user.organization.get_custom_lists_with_options
    @account_types = !custom_lists.blank? ? custom_lists["Account Type"] : {}
    @opportunity_types = !custom_lists.blank? ? custom_lists["Opportunity Type"] : {}

    params[:sort] = ACCOUNT_DASHBOARD_METRIC[:activities_last14d]
    ad_sort_data
  end

  # for loading metrics data (left panel) on Accounts Opportunities Dashboard
  def ad_sort_data
    # puts "\n\n\t************ ad_sort_data *************\n params: #{params}\n\n"

    @metric = params[:sort]

    projects = Project.visible_to(current_user.organization_id, current_user.id)

    # Incrementally apply any filters
    projects = projects.close_date_within(params[:close_date]) unless params[:close_date] == 'Any'
    users_emails = current_user.organization.users.pluck(:email)

    if params[:owner].present?
      if (!params[:owner].include? "None")
        projects = projects.where(owner_id: params[:owner])
      else
        projects = projects.where("\"projects\".owner_id IS NULL OR \"projects\".owner_id IN (?)", params[:owner].select{|o| o != "None"})
      end
    end

    top_dash_projects = projects
    projects = projects.where(stage: params[:stage]) if params[:stage].present?
    projects = projects.where(forecast: params[:forecast]) if params[:forecast].present?

    @this_qtr_range = Project.get_close_date_range(Project::CLOSE_DATE_RANGE[:ThisQuarter])

    @data = [] and return if projects.blank?  #quit early if all projects are filtered out

    # Dashboard top charts
    set_top_dashboard_data(project_ids: top_dash_projects.pluck(:id))

    case @metric
    when ACCOUNT_DASHBOARD_METRIC[:activities_last14d]
      project_engagement = Project.count_activities_by_category(projects.pluck(:id), current_user.organization.domain, users_emails).group_by { |p| p.id }
      @data = [] and @categories = [] and return if project_engagement.blank?

      @data = project_engagement.map do |pid, activities|
        proj = Project.find pid
        Hashie::Mash.new({ id: proj.id, name: proj.name, deal_size: proj.amount, close_date: proj.close_date, y: activities, total: activities.inject(0){|sum,a| sum += (a.num_activities.present? ? a.num_activities : 0)} }) if proj.present?  # else nil
      end

      @data.compact!

      @categories = @data.inject([]) do |memo, d|
        d.y.each {|a| memo = memo | [a.category]}
        memo
      end  # get (and show in legend) only categories that have data
    when ACCOUNT_DASHBOARD_METRIC[:days_inactive]
      last_sent_dates = projects.order("days_inactive DESC").joins(:activities).where.not(activities: { category: [Activity::CATEGORY[:Note], Activity::CATEGORY[:Alert]] }).group("projects.id").select("date_part('day', CURRENT_TIMESTAMP AT TIME ZONE '#{current_user.time_zone}' - MAX(activities.last_sent_date AT TIME ZONE '#{current_user.time_zone}')) AS days_inactive")

      @data = last_sent_dates.map do |d|
        Hashie::Mash.new({ id: d.id, name: d.name, deal_size: d.amount, close_date: d.close_date, y: d.days_inactive, color: 'default' })
      end
    when ACCOUNT_DASHBOARD_METRIC[:open_alerts_and_tasks]
      open_task_counts = Project.count_tasks_per_project(projects.pluck(:id))
      @data = open_task_counts.map do |r|
        Hashie::Mash.new({ id: r.id, name: r.name, deal_size: r.amount, close_date: r.close_date, y: r.open_risks, color: 'default'})
      end
    when ACCOUNT_DASHBOARD_METRIC[:overdue_tasks]
      overdue_tasks = projects.select("COUNT(DISTINCT notifications.id) AS task_count").joins("LEFT JOIN notifications ON notifications.project_id = projects.id AND notifications.category != '#{Notification::CATEGORY[:Attachment]}' AND notifications.is_complete IS FALSE AND EXTRACT(EPOCH FROM notifications.original_due_date) < #{Time.current.to_i}").group("projects.id").order("task_count DESC")
      @data = overdue_tasks.map do |t|
        Hashie::Mash.new({ id: t.id, name: t.name, deal_size: t.amount, close_date: t.close_date, y: t.task_count, color: 'default'})
      end
    when ACCOUNT_DASHBOARD_METRIC[:deal_size]
      deal_size = projects.select("projects.id, projects.name, COALESCE(projects.amount,0) AS deal_size").where("projects.amount > 0")
      @data = deal_size.map do |t|
        Hashie::Mash.new({ id: t.id, name: t.name, deal_size: t.amount, close_date: t.close_date, y: t.deal_size, color: 'default'})
      end
    when ACCOUNT_DASHBOARD_METRIC[:days_to_close]
      @data = projects.select{|p| p.close_date.present?}.map do |p| 
        days_to_close = (p.close_date - Date.today).to_i
        Hashie::Mash.new({ id: p.id, name: p.name, deal_size: p.amount, close_date: p.close_date, y: days_to_close, color: days_to_close < 0 ? 'negative': 'default'})
      end
    else # Invalid  
      @data = []
    end

    if @categories
      @data.sort!{ |d1, d2| (d1.total == d2.total) ? d1.name.upcase <=> d2.name.upcase : d2.total <=> d1.total } # sort using tiebreaker: opportunity name, case-insensitive in alphabetical order
    else  # sort by y instead
      @data.sort!{ |d1, d2| (d1.y != d2.y) ? d2.y <=> d1.y : d1.name.upcase <=> d2.name.upcase }  
    end

    # puts "**************** @data (#{@data.present? ? @data.length : 0}): #{@data} \t\t ****** @categories(#{@categories.present? ? @categories.length : 0}):  #{@categories}"
    @data = @data.take(25)  # TODO: real left chart pagination
  end

  # for loading opportunity drill-down (right panel) on Opportunities Dashboard ("account" in this case is an opportunities, internally known as a project)
  def ad_account_data
    @project = Project.visible_to(current_user.organization_id, current_user.id).find(params[:id])

    #@risk_score = @project.new_risk_score(current_user.time_zone)
    @open_tasks_count = @project.notifications.open.count
    # @last_activity_date = @project.activities.where.not(category: [Activity::CATEGORY[:Note], Activity::CATEGORY[:Alert]]).maximum("activities.last_sent_date")
    #@risk_score_trend = @project.new_risk_score_trend(current_user.time_zone)

    # Alerts & Tasks
    @alerts_tasks = @project.notifications.order(:is_complete, :created_at).limit(8)
    # Next Meeting
    @next_meeting = @project.meetings.next_week.last
    # Next Steps
    @ns_activity = @project.activities.where(category: Activity::CATEGORY[:NextSteps]).first

    # Engagement Volume Chart
    # @activities_moving_avg = @project.activities_moving_average(current_user.time_zone)
    @activities_by_category_date = @project.daily_activities_in_date_range(current_user.time_zone).group_by { |a| a.category }

    #TODO: Query for usage_report finds all the read and write times from internal users
    #Metric for Interaction Time
    @interaction_time_report = @project.interaction_time_by_user(current_user.organization.users)

    # TODO: Modify query and method params for count_activities_by_user_flex to take project_ids instead of account_ids
    # Most Active Contributors & Activities By Team
    user_num_activities = User.count_activities_by_user_flex([@project.account.id], current_user.organization.domain)
    @team_leaderboard = []
    @activities_by_dept = Hash.new(0)
    activities_by_dept_total = 0
    user_num_activities.each do |u|
      user = User.find_by_email(u.email)
      u.email = get_full_name(user) if user
      @team_leaderboard << u
      dept = user.nil? || user.department.nil? ? '(unknown)' : user.department
      @activities_by_dept[dept] += u.inbound_count + u.outbound_count
      activities_by_dept_total += u.inbound_count + u.outbound_count
    end
    # Convert Activities By Team to %
    @activities_by_dept.each { |dept, count| @activities_by_dept[dept] = (count.to_f/activities_by_dept_total*100).round(1)  }
    # Only show top 5 for Most Active Contributors
    @team_leaderboard = @team_leaderboard[0...5]

    render layout: false
  end

  def team_dashboard
    users = current_user.organization.users
    @departments = users.registered.pluck(:department).reject(&:blank?).uniq
    @titles = users.registered.pluck(:title).reject(&:blank?).uniq

    params[:sort] = TEAM_DASHBOARD_METRIC[:win_rate]
    params[:metric] = TEAM_DASHBOARD_METRIC[:time_spent_last14d]
    td_sort_data
  end

  # for loading metrics data (left panel) on Leaderboard/Team Dashboard
  def td_sort_data
    # puts "\n\n\t************ td_sort_data *************\n params: #{params}\n\n"

    # NOTE: `sort` and `sort_by` are keywords for Hash, would have used these as keys for @dashboard_data but can't due to this conflict!
    @dashboard_data = Hashie::Mash.new(sorted_by: { type: params[:sort] }, metric: { type: params[:metric] })
    users = current_user.organization.users.registered.onboarded

    # Incrementally apply filters
    if params[:team].present?
      if (!params[:team].include? "(None)")
        users = users.where(department: params[:team])
      else

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/ad_account_data.html.erb
<div id="account-header">
    <div class="row m-b-sm">
        <div class="col-lg-12">
            <h2><a href="<%= project_path(@project) %>"><%= @project.name %></a></h2>
        </div>
    </div>

    <div class="ibox-content">
        <div class="row">
            <div class="col-md-3 text-center">
                <div class="metric">
                    <div class="metric-title">
                        <h4><%= Project::MAPPABLE_FIELDS_META["stage"] %></h4>
                    </div>
                    <div class="metric-content">
                        <h2 style="margin:20px 0"><%= @project.stage.blank? ? "-" : @project.stage %></h2>
                    </div>
                </div>
            </div>

            <div class="col-md-3 text-center">
                <div class="metric">
                    <div class="metric-title">
                        <h4>Days to Close</h4>
                    </div>
                    <div class="metric-content">
                        <h2 style="font-weight:600;font-size:46px"><%= @project.close_date.nil? ? "-" : (@project.close_date - Date.today).to_i %></h2>
                    </div>
                </div>
            </div>

            <div class="col-md-3 text-center">
                <div class="metric">
                    <div class="metric-title">
                        <h4><%= Project::MAPPABLE_FIELDS_META["amount"] %></h4>
                    </div>
                    <div class="metric-content">
                        <h2 style="font-weight:600;font-size:46px;"><%= @project.amount.nil? ? "-" : "$"+number_to_human(@project.amount) %></h2>
                    </div>
                </div>
            </div>

            <div class="col-md-3 text-center">
                <div class="metric text-danger">
                    <div class="metric-title">
                        <h4>Open Alerts & Tasks</h4>
                    </div>
                    <div class="metric-content">
                        <h2 style="font-weight:600;font-size:46px"><%= @open_tasks_count %></h2>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
<!-- end id="account-header" -->

<div id="account-charts">
    <div class="ibox-content">
        <div class="row m-t-md">
            <h3><i class="fa fa-bell-o" aria-hidden="true"></i>&nbsp;&nbsp;Alerts & Tasks <% if @alerts_tasks.length == 8 %>(Most Recent 8)<% end %></h3>
            <% if @alerts_tasks.present? %>
            <ul class="todo-list m-t">
                <% @alerts_tasks.each do |n| %>
                <li>
                    <input type="checkbox" class="i-checks" id=<%= n.id %> <% if n.is_complete %> checked <% end %> >
                    <%= n.name %>
                    <% labels = { Notification::CATEGORY[:Action] => 'label-primary',
                                     Notification::CATEGORY[:Opportunity] => 'label-success',
                                     Notification::CATEGORY[:Todo] => 'label-info',
                                     Notification::CATEGORY[:Alert] => 'label-danger' }
                       not_label = labels[n.category]
                    %>
                    <small class="label <%= not_label %>"><%= n.category %></small>
                    <% if n.original_due_date.present? %>
                    <small class="label label-primary"><i class="fa fa-clock-o"></i> Due <%= Time.zone.at(n.original_due_date).strftime('%b %e') %></small>
                    <% end %>
                </li>
                <% end %>
            </ul>
            <% else %>
            <p class="text-danger">No Alerts & Tasks.</p>
            <% end %>
        </div>

        <div class="row m-t-md">
            <h3 class="m-t-md"><i class="fa fa-chevron-right"></i>  Next Steps:</h3>
            <% if @project.next_steps.present? %>
              <%= simple_format(CGI.escape_html(@project.next_steps)) %>
              <p class="text-muted"><%= @ns_activity.blank? ? '' : 'Updated ' + time_ago_in_words(Time.zone.at(@ns_activity.last_sent_date).strftime('%b %d, %R%P')) + ' ago' %></p>
            <% else %>
              <p class="text-danger">No next steps set yet.</p>
            <% end %>
        </div>

        <div class="row m-t-md">
            <h3 class="m-t-md"><i class="fa fa-calendar"></i>  Next Meeting:</h3>
            <% if @next_meeting.present? %>
            <p>
              <strong><%= @next_meeting.title %></strong>
              <%= Time.zone.at(@next_meeting.last_sent_date).strftime('%b %d, %R%P') %>
            </p>
            <% else %>
            <p class="text-danger">No meetings set up.</p>
            <% end %>
        </div>

        <div class="row m-t-md text-center">
            <h3><%= link_to "See Alerts & Next Steps &rarr;".html_safe, tasks_project_path(@project), class: "btn btn-outline btn-primary btn-xs" %></h3>
        </div>
    </div>

    <div id="charts-container" class="ibox-content">

        <div class="row m-t-md">
            <div id="project-activities-trend-chart"></div>
        </div>

        <div class="row m-t-lg text-center">
            <h3><%= link_to "See activities &rarr;".html_safe, project_path(@project), class: "btn btn-outline btn-primary btn-xs" %></h3>
        </div>
    </div>

    <div class="ibox-content">
        <div class="row">
            <div class="col-lg-6" id="activities-breakdown" style="height:200px"></div>
            <div class="col-lg-6" id="usage-report" style="height:200px;"></div>
        </div>

        <div class="row m-t-lg text-center">
            <h3><%= link_to "See Account Relationship Graph &rarr;".html_safe, arg_project_path(@project), class: "btn btn-outline btn-primary btn-xs" %></h3>
        </div>
    </div>
</div>
<script type="text/javascript">

    // initialize iCheck for dynamically added Notifications
    $('.i-checks').iCheck({checkboxClass: 'icheckbox_square-green'});

    /*****
    Render right charts
    ******/

    function renderProjectCharts(riskScore) {

        $('#activities-breakdown').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            credits: false,
            title: {
                text: "Activities By Team",
                align: 'left',
                margin: 0,
                x: 35,
                style: {
                    color: '#555555',
                    fontSize: '16px'
                }
            },
            tooltip: {
                pointFormat: '{point.percentage:.1f}%'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        distance: 10,
                        style: {
                            fontSize: 10,
                            fontWeight: 'normal'
                        },
                        format: '{point.name}',
                    }
                }
            },
            series: [{
                name: 'Team',
                colorByPoint: true,
                data: [
                <% @activities_by_dept.each do |dept, count| %>
                {
                    name: "<%= dept %>",
                    y: <%= count %>
                },
                <% end %>
                ]
            }]
        });

        $('#usage-report').highcharts({
            chart: {
                type: 'bar',
                marginRight: 35
            },
            title: {
                text: 'Interaction Time',
                align: 'center',
                margin: 0,
                style: {
                    color: '#555555',
                    fontSize: '16px'
                }
            },
            subtitle: {
                text: '(Estimated time in hh:mm, last 14 days)',
                align: 'center',
                style: {
                    fontSize: '10px'
                }
            },
            credits: { enabled: false },
            xAxis: {
                categories: <%= @interaction_time_report.map(&:name).to_json.html_safe %>
            },
            yAxis: {
                min: 0,
                minTickInterval: 60,
                title: {
                    enabled: false
                },
                labels: {
                    formatter: function () {
                        return convert_secs_to_hhmm(this.value);
                    }
                },
                stackLabels: {
                    enabled: true,
                    formatter: function () {
                        return convert_secs_to_hhmm(this.total);
                    }
                }
            },
            legend: {
                enabled: false
            },
            tooltip: {
                headerFormat: '',
                // pointFormat: '<b>{series.name}:</b> {point.y:.2f} hrs<br/><b>Total:</b> {point.stackTotal:.2f} hrs'
                pointFormatter: function() {
                  return '<span style="color:' + this.color + '">\u25CF</span>  <b>' + this.series.name + '</b>: ' + convert_secs_to_hhmm(this.y) + '<br/>'+ '<b>Total</b>: ' + convert_secs_to_hhmm(this.total) + '<br/>';
                }
            },

            plotOptions: {
                series: {
                    stacking: 'normal',
                    dataLabels: {
                        format: '{y.2f}',
                        style: {
                            fontWeight: 'bold',
                            fontSize: '8px'
                        }
                    }
                }
            },
            series: [
              <% %i(Meetings Attachments Sent\ E-mails Read\ E-mails).each do |category| %>
              {
                name: '<%= category %>',
                color: "<%= highcharts_series_color(category.to_s) %>",
                data: <%= @interaction_time_report.map(&category).to_json.html_safe %>
              },
              <% end %>
            ]
        });

        $('#project-activities-trend-chart').highcharts({
            chart: {
                height: 240,
                events:{
                  load: function(event) {
                    var extremes = this.yAxis[0].getExtremes();
                    if(extremes.dataMax == 0){
                      extremes.max = 1;
                      this.yAxis[0].setExtremes(0,1);
                    } else{
                      this.yAxis[0].setExtremes(0, extremes.dataMax);
                    }
                    }
                }
            },
            credits: {
                enabled: false
            },
            title: {
                text: "Activities (Last 14 days)",
                    align: 'left',
                    margin: 0,
                    x: 35,
                    style: {
                        color: '#555555',
                        fontSize: '16px'
                    }
            },
            xAxis: {
                type: 'datetime',
            },
            yAxis: {
                title: { text: '' },
                labels: { enabled: true },
                minTickInterval: 1,
                minorGridLineWidth: 0,
                min: 0,
                stackLabels: {
                    enabled: true
                }
            },
            legend: {
                enabled: true
            },
            plotOptions: {
                series: {
                    stacking: 'normal'
                }
            },
            series: [
            <% @activities_by_category_date.each do |category, activities_by_date| %>
            {
                type: 'column',
                name: '<%= category %>',
                color: '<%= highcharts_series_color(category) %>',
                pointInterval: <%= 1.day * 1000 %>,
                pointStart: <%= 14.days.ago.at_midnight.to_i * 1000 %>,
                data: <%= activities_by_date.map(&:num_activities).to_json.html_safe %>,
                showInLegend: <%= activities_by_date.map(&:num_activities).reduce(:+) > 0 ? true : false %>
            },
            <% end %>
            ]
        });
    };

</script>

app/views/reports/lifecycle.html.erb
<h1>Reports#lifecycle</h1>
<p>Find me in app/views/reports/lifecycle.html.erb</p>